import type { StreetLightSpec, TerrainSpec } from '@domain/map/MapManifest';
import { elevationAt } from '@domain/map/elevation';
import { Glow, LightPool } from './environment/Glow';
import { useLightsOn } from './environment/environmentStore';

/**
 * Streetlights placed from the manifest (one per road segment, generated by the
 * city builder). Each is a pole with a lamp head that glows warm at night — a
 * halo in the air plus a pool of light on the asphalt — and is dark by day.
 * Map-agnostic: a new map's streetlights render with zero code change.
 */

const POLE_HEIGHT = 5.4;
const LAMP_COLOR = '#ffce82';

export function StreetLights({ lights, terrain }: { lights: StreetLightSpec[]; terrain: TerrainSpec }) {
  const lightsOn = useLightsOn();
  return (
    <>
      {lights.map((spec, i) => (
        <StreetLight key={i} spec={spec} terrain={terrain} lightsOn={lightsOn} />
      ))}
    </>
  );
}

function StreetLight({
  spec,
  terrain,
  lightsOn,
}: {
  spec: StreetLightSpec;
  terrain: TerrainSpec;
  lightsOn: boolean;
}) {
  const baseY = elevationAt(terrain, spec.x, spec.z);
  return (
    <group position={[spec.x, baseY, spec.z]}>
      {/* Pole */}
      <mesh position={[0, POLE_HEIGHT / 2, 0]} castShadow>
        <cylinderGeometry args={[0.08, 0.11, POLE_HEIGHT, 8]} />
        <meshStandardMaterial color="#2a2e35" />
      </mesh>
      {/* Lamp head */}
      <mesh position={[0, POLE_HEIGHT, 0]}>
        <boxGeometry args={[0.42, 0.2, 0.42]} />
        <meshStandardMaterial
          color="#1a1c20"
          emissive={lightsOn ? LAMP_COLOR : '#000000'}
          emissiveIntensity={lightsOn ? 1.8 : 0}
        />
      </mesh>
      {lightsOn && (
        <>
          <Glow position={[0, POLE_HEIGHT - 0.1, 0]} color={LAMP_COLOR} size={3.4} opacity={0.85} />
          <LightPool position={[0, 0.07, 0]} color={LAMP_COLOR} radius={6.5} opacity={0.5} />
        </>
      )}
    </group>
  );
}
